name: pdf-to-excel-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - werkzeug=2.3.7
  - numpy=1.24.3
  - pillow=10.0.0
  - opencv=4.8.0
  - poppler=23.07.0
  - flask-cors=4.0.0
  - pyPdf2=3.0.1
  - openpyxl=3.1.2
  - python-dotenv=1.0.0
  - pip=23.1.2